# Nom i cognoms: Victor Girones De Asix
# Data: 04/11/2025
# Descripció:
# Especificació de la tasca: Escriu una funció saluda_nom(nom="amic") que imprimeixi "Hola, <nom>". Si no passes cap nom, ha de imprimir "Hola, amic".

def saluda_nom(nom="amic"):
    print(f"Hola, {nom}!")
saluda_nom("Maria")
saluda_nom()
saluda_nom("Pere")
saluda_nom("Anna")
saluda_nom()
saluda_nom("Carlos")
saluda_nom("Sofia")